name:                Geo-Forward
version:             0.06
version_from:        lib/Geo/Forward.pm
abstract:            Perl version of forward calculations
license:             perl
distribution_type:   module
requires:     
    vars:                          0
    strict:                        0
