--- #YAML:1.0
name:                Geo-Forward
version:             0.13
abstract:            Calculate geographic location from lat, lon, distance, and heading.
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Geo::Constants:                0.04
    Geo::Ellipsoids:               0.09
    Geo::Functions:                0.03
    Package::New:                  0
    Test::Simple:                  0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
